// Code generated by protoc-gen-ginstruct. DO NOT EDIT.
// source: skill/skill.proto

package gen

type CreateSkillRequest struct {
	Name         string   `json:"name" binding:"required"`
	Description  string   `json:"description" binding:"required"`
	Instructions string   `json:"instructions" binding:"required"`
	Editors      []string `json:"editors"`
}

type UpdateSkillRequest struct {
	Name                string `json:"name"`
	Description         string `json:"description"`
	Instructions        string `json:"instructions"`
	ExpectedContentHash string `json:"expectedContentHash,omitempty"`
}

type SkillWorkspaceResponse struct {
	Editors  []string              `json:"editors"`
	Skill    SkillProductResponse  `json:"skill"`
	Active   SkillRevisionResponse `json:"active"`
	HasDraft bool                  `json:"hasDraft"`
}

type SkillProductResponse struct {
	ID               string `json:"id"`
	Name             string `json:"name"`
	Description      string `json:"description"`
	Status           string `json:"status"`
	ActiveRevisionID string `json:"activeRevisionId,omitempty"`
	IsSystem         bool   `json:"isSystem"`
}

type SkillRevisionResponse struct {
	ID               string         `json:"id"`
	SkillID          string         `json:"skillId"`
	RevisionNo       int32          `json:"revisionNo,omitempty"`
	Status           string         `json:"status"`
	Name             string         `json:"name"`
	Description      string         `json:"description"`
	Instructions     string         `json:"instructions"`
	PublishChecks    map[string]any `json:"publishChecks,omitempty"`
	IsCurrent        bool           `json:"isCurrent"`
	CreatedBy        string         `json:"createdBy"`
	CreatedAt        string         `json:"createdAt,omitempty"`
	ContentHash      string         `json:"contentHash,omitempty"`
	CreatedByName    string         `json:"createdByName"`
	ParentRevisionID string         `json:"parentRevisionId,omitempty"`
}

type SkillRevisionsResponse struct {
	Revisions []SkillRevisionResponse `json:"revisions"`
}

type RollbackSkillRequest struct {
	RevisionID string `json:"revisionId" binding:"required"`
}

type ErrorResponse struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

type SaveSkillDraftRequest struct {
	Name                string `json:"name"`
	Description         string `json:"description"`
	Instructions        string `json:"instructions"`
	ExpectedContentHash string `json:"expectedContentHash,omitempty"`
}

type PublishSkillDraftRequest struct {
	ExpectedContentHash string `json:"expectedContentHash,omitempty"`
}
